# Generated by Django 5.1.3 on 2024-12-01 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Lower', 'Lower'), ('Upper', 'Upper'), ('Sixth Form', 'Sixth Form')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClassYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.level')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('class_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='reports.classyear')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('class_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.classyear')),
                ('subjects', models.ManyToManyField(to='reports.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_name', models.CharField(max_length=100)),
                ('class_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.classyear')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.term'),
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continuous_assessment', models.FloatField()),
                ('exam_score', models.FloatField()),
                ('total_score', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.term')),
            ],
        ),
    ]
