# Generated by Django 5.1.3 on 2024-12-01 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_classyear_level_alter_score_student_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classyear',
            options={'verbose_name': 'Class / Year', 'verbose_name_plural': 'Classes / Years'},
        ),
    ]
