# Generated by Django 5.1.3 on 2024-12-01 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_classyear_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(choices=[('Lower Secondary', 'Lower Secondary'), ('Upper Secondary', 'Upper Secondary'), ('Sixth Form', 'Sixth Form')], max_length=100),
        ),
        migrations.AlterField(
            model_name='term',
            name='term_name',
            field=models.CharField(choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3')], max_length=100),
        ),
    ]
