# Generated by Django 5.1.3 on 2024-12-01 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_level_name_alter_term_term_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='class_year',
        ),
        migrations.AddField(
            model_name='subject',
            name='class_year',
            field=models.ManyToManyField(related_name='subjects', to='reports.classyear'),
        ),
    ]
