# Generated by Django 5.1.3 on 2024-12-01 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_remove_subject_class_year_subject_class_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='term',
        ),
    ]
