# Generated by Django 5.1.3 on 2024-12-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_student_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='continuous_assessment',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='score',
            name='exam_score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='score',
            name='total_score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
