# Generated by Django 5.1.3 on 2024-12-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_score_continuous_assessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='grade',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
