# Generated by Django 5.1.3 on 2024-12-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_rename_user_score_created_by_score_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicreport',
            name='student_score',
        ),
        migrations.AddField(
            model_name='academicreport',
            name='student_scores',
            field=models.ManyToManyField(related_name='academic_reports', to='reports.score'),
        ),
    ]
