# Generated by Django 4.2.16 on 2025-02-08 17:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_remove_academicreport_student_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='class_work_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='score',
            name='midterm_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='score',
            name='progressive_test_1_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='score',
            name='progressive_test_2_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='score',
            name='progressive_test_3_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='score',
            name='continuous_assessment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='score',
            name='total_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5),
        ),
    ]
