# Generated by Django 4.2.16 on 2025-02-22 16:02

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0014_score_class_work_score_score_midterm_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicreport',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='academicreport',
            name='student_gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='class_work_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=100),
        ),
        migrations.AlterField(
            model_name='score',
            name='continuous_assessment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=25),
        ),
        migrations.AlterField(
            model_name='score',
            name='exam_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=100),
        ),
        migrations.AlterField(
            model_name='score',
            name='grade',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='score',
            name='midterm_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=100),
        ),
        migrations.AlterField(
            model_name='score',
            name='progressive_test_1_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=100),
        ),
        migrations.AlterField(
            model_name='score',
            name='progressive_test_2_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=100),
        ),
        migrations.AlterField(
            model_name='score',
            name='progressive_test_3_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=100),
        ),
        migrations.AlterField(
            model_name='score',
            name='total_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=100),
        ),
        migrations.CreateModel(
            name='ProgressiveTestTwoReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progressive_test2_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_progressive_test2_reports', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressive_test2_reports', to='reports.student')),
                ('student_scores', models.ManyToManyField(related_name='progressive_test2_reports', to='reports.score')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressive_test2_reports', to='reports.term')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressiveTestThreeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progressive_test3_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_progressive_test3_reports', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressive_test3_reports', to='reports.student')),
                ('student_scores', models.ManyToManyField(related_name='progressive_test3_reports', to='reports.score')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressive_test3_reports', to='reports.term')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressiveTestOneReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progressive_test1_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_progressive_test1_reports', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressive_test1_reports', to='reports.student')),
                ('student_scores', models.ManyToManyField(related_name='progressive_test1_reports', to='reports.score')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressive_test1_reports', to='reports.term')),
            ],
        ),
        migrations.CreateModel(
            name='MidtermReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('midterm_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_midterm_reports', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midterm_reports', to='reports.student')),
                ('student_scores', models.ManyToManyField(related_name='midterm_reports', to='reports.score')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midterm_reports', to='reports.term')),
            ],
        ),
    ]
