# Generated by Django 4.2.16 on 2025-02-23 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_academicreport_generated_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicreport',
            options={'verbose_name': 'End of Term Report ', 'verbose_name_plural': 'End of Term Reports'},
        ),
        migrations.AlterModelOptions(
            name='midtermreport',
            options={'verbose_name': 'Midterm Report', 'verbose_name_plural': 'Midterm Reports'},
        ),
        migrations.AlterModelOptions(
            name='progressivetestonereport',
            options={'verbose_name': 'Progressive One Report ', 'verbose_name_plural': 'Progressive One Reports'},
        ),
        migrations.AlterModelOptions(
            name='progressivetestthreereport',
            options={'verbose_name': 'Progressive Three Report', 'verbose_name_plural': 'Progressive Three Reports'},
        ),
        migrations.AlterModelOptions(
            name='progressivetesttworeport',
            options={'verbose_name': 'Progressive Two Report', 'verbose_name_plural': 'Progressive Two Reports'},
        ),
    ]
