# Generated by Django 4.2.16 on 2025-03-17 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_mockscore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MockScore',
        ),
    ]
