# Generated by Django 4.2.16 on 2025-03-17 14:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0020_delete_mockscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='mock_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=100),
        ),
    ]
