# Generated by Django 4.2.16 on 2025-03-19 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0021_score_mock_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mock_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_mock_reports', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_reports', to='reports.student')),
                ('student_scores', models.ManyToManyField(related_name='mock_reports', to='reports.score')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_reports', to='reports.term')),
            ],
            options={
                'verbose_name': 'Mock Report',
                'verbose_name_plural': 'Mock Reports',
            },
        ),
    ]
