# Generated by Django 5.1.3 on 2025-06-27 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0022_mockreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='progressive_test_3_score',
        ),
        migrations.DeleteModel(
            name='ProgressiveTestThreeReport',
        ),
    ]
