# Generated by Django 5.1.3 on 2025-06-27 14:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0023_remove_score_progressive_test_3_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='progressive_test_3_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=100),
        ),
    ]
