# Generated by Django 5.1.3 on 2025-06-27 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0025_academicreport_comment_midtermreport_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('report_type', models.CharField(choices=[('final', 'Final'), ('midterm', 'Midterm'), ('mock', 'Mock'), ('progressive1', 'Progressive Test 1'), ('progressive2', 'Progressive Test 2')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.term')),
            ],
            options={
                'unique_together': {('student', 'term', 'report_type')},
            },
        ),
    ]
