# Generated by Django 5.1.3 on 2025-06-27 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0026_reportcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportComment',
        ),
    ]
