# Generated by Django 5.1.3 on 2025-06-28 10:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0027_delete_reportcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('student', 'subject', 'term', 'created_by')},
        ),
    ]
