# Generated by Django 5.1.3 on 2025-07-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0028_alter_score_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='is_head_class_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
