# Generated by Django 5.1.3 on 2025-07-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0029_teacherprofile_is_head_class_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicreport',
            old_name='comment',
            new_name='academic_comment',
        ),
        migrations.AddField(
            model_name='academicreport',
            name='behavioral_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicreport',
            name='promotion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
