# Generated by Django 5.1.3 on 2025-08-01 15:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0030_rename_comment_academicreport_academic_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='academicreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='academicreport',
            name='promotion',
            field=models.CharField(blank=True, choices=[('Year 7 (Lower Secondary)', 'Year 7 (Lower Secondary)'), ('Year 8 (Lower Secondary)', 'Year 8 (Lower Secondary)'), ('Year 9 (Lower Secondary)', 'Year 9 (Lower Secondary)'), ('Year 10 (Upper Secondary)', 'Year 10 (Upper Secondary)'), ('Year 11 (Upper Secondary)', 'Year 11 (Upper Secondary)'), ('Year 12 (Sixth Form)', 'Year 12 (Sixth Form)'), ('Year 13 (Sixth Form)', 'Year 13 (Sixth Form)')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='academicreport',
            name='student_scores',
            field=models.ManyToManyField(blank=True, related_name='academic_reports', to='reports.score'),
        ),
        migrations.AlterUniqueTogether(
            name='academicreport',
            unique_together={('student', 'term')},
        ),
    ]
