# Generated by Django 5.1.3 on 2025-12-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0031_academicreport_created_at_academicreport_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='grading_system',
            field=models.CharField(choices=[('standard', 'Standard Grading System'), ('cambridge', 'Cambridge Grading System')], default='standard', help_text='Select the grading system for this subject', max_length=20),
        ),
    ]
