# Generated by Django 5.1.3 on 2025-12-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0032_subject_grading_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='academic_comment',
            field=models.TextField(blank=True, help_text='Academic comment by head class teacher', null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='behavioral_comment',
            field=models.TextField(blank=True, help_text='Behavioral comment by head class teacher', null=True),
        ),
    ]
