# Generated by Django 5.1.3 on 2025-12-17 09:31

from django.db import migrations


def migrate_comments_to_new_model(apps, schema_editor):
    """Migrate existing comments from Score model to StudentReportComment model"""
    Score = apps.get_model('reports', 'Score')
    StudentReportComment = apps.get_model('reports', 'StudentReportComment')
    Student = apps.get_model('reports', 'Student')
    Term = apps.get_model('reports', 'Term')

    # Get all students who have scores
    students_with_scores = Student.objects.filter(scores__isnull=False).distinct()

    migrated_count = 0

    for student in students_with_scores:
        # Get all terms this student has scores for
        terms = Term.objects.filter(scores__student=student).distinct()

        for term in terms:
            # Find any score with comments for this student in this term
            academic_comment = ''
            behavioral_comment = ''
            created_by = None

            scores_with_comments = Score.objects.filter(
                student=student,
                term=term
            ).exclude(
                academic_comment__isnull=True,
                academic_comment=''
            ) | Score.objects.filter(
                student=student,
                term=term
            ).exclude(
                behavioral_comment__isnull=True,
                behavioral_comment=''
            )

            for score in scores_with_comments:
                if not academic_comment and score.academic_comment:
                    academic_comment = score.academic_comment
                if not behavioral_comment and score.behavioral_comment:
                    behavioral_comment = score.behavioral_comment
                if not created_by and score.created_by:
                    created_by = score.created_by

                # Break if we found both
                if academic_comment and behavioral_comment:
                    break

            # Create StudentReportComment if we found any comments
            if academic_comment or behavioral_comment:
                StudentReportComment.objects.get_or_create(
                    student=student,
                    term=term,
                    defaults={
                        'academic_comment': academic_comment,
                        'behavioral_comment': behavioral_comment,
                        'created_by': created_by
                    }
                )
                migrated_count += 1

    print(f"Migrated comments for {migrated_count} student-term combinations")


def reverse_migration(apps, schema_editor):
    """Reverse migration - delete all StudentReportComment records"""
    StudentReportComment = apps.get_model('reports', 'StudentReportComment')
    StudentReportComment.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0034_studentreportcomment'),
    ]

    operations = [
        migrations.RunPython(migrate_comments_to_new_model, reverse_migration),
    ]
