# Generated by Django 5.1.3 on 2025-12-17 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0035_migrate_comments_to_new_model'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentreportcomment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentreportcomment',
            name='class_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_comments', to='reports.classyear'),
        ),
        migrations.AlterUniqueTogether(
            name='studentreportcomment',
            unique_together={('student', 'class_year', 'term')},
        ),
    ]
