# Generated by Django 5.1.3 on 2025-12-17 13:29

from django.db import migrations


def populate_class_year(apps, schema_editor):
    """Populate class_year field from student's class_year"""
    StudentReportComment = apps.get_model('reports', 'StudentReportComment')

    updated_count = 0
    for comment in StudentReportComment.objects.all():
        if comment.student and comment.student.class_year:
            comment.class_year = comment.student.class_year
            comment.save()
            updated_count += 1

    print(f"Populated class_year for {updated_count} comment records")


def reverse_populate(apps, schema_editor):
    """Reverse migration - set all class_year to None"""
    StudentReportComment = apps.get_model('reports', 'StudentReportComment')
    StudentReportComment.objects.update(class_year=None)


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0036_alter_studentreportcomment_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_class_year, reverse_populate),
    ]
