# Generated by Django 5.1.3 on 2025-12-17 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0037_populate_comment_class_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockReportComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_comment', models.TextField(blank=True, default='')),
                ('behavioral_comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_report_comments', to='reports.classyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_report_comments', to='reports.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_report_comments', to='reports.term')),
            ],
            options={
                'verbose_name': 'Mock Report Comment',
                'verbose_name_plural': 'Mock Report Comments',
                'unique_together': {('student', 'class_year', 'term')},
            },
        ),
    ]
